### ISSUE TITLE
Coupling

### ISSUE THREAD

**Issue by keramat-farid** [farbodbj/GuardianNews#14] opened 2023-08-15 06:13 UTC
This logic must be inside you data base class or inside a provider block if you are using hilt

https://github.com/farbodbj/GuardianNews/blob/1ff5d7e1cf82eaffe30e24b5a9e17030fdd5e615/app/src/main/java/com/bale_bootcamp/guardiannews/GuardianNewsApp.kt#L14C14-L14C14

**Comment by farbodbj** [comment] 2023-08-16 15:41
this issue has been addressed in commit: be9a79cc (commit message: "bugs caused by DI merge fixed")

**Closed as completed by farbodbj** 2023-08-16 15:41 UTC
